# Generated by Django 3.2.3 on 2021-07-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='desc',
            field=models.TextField(max_length=200),
        ),
    ]
