# Generated by Django 3.2.3 on 2021-07-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0002_alter_tache_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tache',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Running', 'Running'), ('Paused', 'Paused'), ('Done', 'Done')], default='Open', max_length=7, null=True),
        ),
    ]
