# Generated by Django 3.2.3 on 2021-07-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_employe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='prenom',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
